version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd app && npm start"
    ports:
      - "3000:3000"